[package]
name = "agent_api_rest"
version = "0.1.0"
edition = "2021"

[dependencies]
agent_issuance = { path = "../agent_issuance" }
agent_store = { path = "../agent_store" }

cqrs-es = "0.4.2"

oid4vci = { git = "https://git@github.com/impierce/openid4vc.git", branch = "feat/refactor-request" }
oid4vc-core = { git = "https://git@github.com/impierce/openid4vc.git", branch = "feat/refactor-request" }

axum = "0.6"
axum-macros = "0.3"
axum-auth = "0.4"
serde_json = "1.0"
hyper = { version = "0.14", features = ["full"] }

[dev-dependencies]
mime = { version = "0.3" }
tokio = { version = "1.34", features = ["full"] }
tower = { version = "0.4" }
