[workspace]

members = [
    "agent_api_rest",
    "agent_application",
    "agent_issuance",
    "agent_store",
]

[workspace.dependencies]
lazy_static = "1.4"
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = { version = "1.0" }
