[workspace]
resolver = "2"
members = ["agent_api", "agent_core", "agent_storage"]

[workspace.dependencies]
identity_core = { version = "=1.0.0-rc.1" }
identity_credential = { version = "=1.0.0-rc.1", default-features = false, features = [
    "credential",
] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = { version = "1.0", default-features = false }
thiserror = { version = "1.0", default-features = false }
time = { version = "0.3" }

[workspace.package]
edition = "2021"
license = "Apache-2.0"
rust-version = "1.70.0"
