[workspace]

members = [
    "agent_api_rest",
    "agent_application",
    "agent_issuance",
    "agent_store",
]

[workspace.dependencies]
lazy_static = "1.4"
uuid = { version = "1.4", features = ["v4", "fast-rng", "serde"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = { version = "1.0" }
thiserror = "1.0"
url = "2.5"
