[package]
name = "agent_issuance"
version = "0.1.0"
edition = "2021"

[dependencies]
oid4vci = { git = "https://git@github.com/impierce/openid4vc.git", branch = "feat/refactor-request" }
oid4vc-core = { git = "https://git@github.com/impierce/openid4vc.git", branch = "feat/refactor-request" }
oid4vc-manager = { git = "https://git@github.com/impierce/openid4vc.git", branch = "feat/refactor-request" }

cqrs-es = "0.4.2"

async-trait = "0.1"
derivative = "2.2"
did-key = "0.2"
jsonschema = "0.17"
jsonwebtoken = "8.2"
serde.workspace = true
serde_json = "1.0"
url.workspae = true
uuid = { version = "1.4", features = ["v4", "fast-rng", "serde"] }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
serde.workspace = true
lazy_static.workspace = true
