[package]
name = "agent_issuance"
version = "0.1.0"
edition = "2021"

[dependencies]
agent_store = { path = "../agent_store" }

oid4vci = { git = "https://git@github.com/impierce/openid4vc.git", branch = "feat/refactor-request" }
oid4vc-core = { git = "https://git@github.com/impierce/openid4vc.git", branch = "feat/refactor-request" }

cqrs-es = "0.4.2"
sqlx = { version = "0.7", features = [
    "postgres",
    "runtime-tokio-rustls",
    "json",
] }
async-trait = "0.1.52"
serde.workspace = true
serde_json = "1.0"
jsonschema = "0.17"


identity_credential = { git = "https://github.com/iotaledger/identity.rs.git", default-features = false, features = [
    "credential",
] }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
serde.workspace = true
lazy_static.workspace = true
url = "2.4"
