[package]
name = "agent_issuance"
version = "0.1.0"
edition = "2021"

[dependencies]
agent_store = { path = "../agent_store" }

cqrs-es = "0.4.2"
sqlx = { version = "0.7", features = [ "postgres" , "runtime-tokio-rustls", "json"] }
async-trait = "0.1.52"
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
jsonschema = "0.17"

identity_credential = { git = "https://github.com/iotaledger/identity.rs.git", default-features = false, features = [
    "credential",
] }

# TODO: remove this once handlers.rs is removed.
axum = "0.6"


[dev-dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"]}
