[package]
name = "agent_application"
version = "0.1.0"
edition = "2021"

[dependencies]
agent_issuance = { path = "../agent_issuance" }
agent_api_rest = { path = "../agent_api_rest" }
agent_store = { path = "../agent_store" }

cqrs-es = "0.4.2"
axum = "0.6"
tokio = { version = "1.34", features = ["full"] }
