version: "3.1"

name: ssi-agent

services:
  cqrs-postgres-db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo_pass
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
  pg-admin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5433:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - "./db/pgadmin4/servers.json:/pgadmin4/servers.json"
    depends_on:
      - cqrs-postgres-db
  ssi-agent:
    #image: ssi-agent
    build:
      context: ../..
      dockerfile: ./agent_application/docker/Dockerfile
    ports:
      - 3033:3033
    environment:
      # AGENT_CONFIG_LOG_FORMAT: json
      AGENT_CONFIG_EVENT_STORE: postgres
      # AGENT_CONFIG_BASE_PATH: "unicore"
      AGENT_APPLICATION_URL: http://192.168.1.127:3033
      AGENT_STORE_DB_CONNECTION_STRING: postgresql://demo_user:demo_pass@cqrs-postgres-db:5432/demo
      AGENT_CONFIG_STRONGHOLD_PATH: /app/res/stronghold
      AGENT_CONFIG_STRONGHOLD_PASSWORD: "secure_password"
    volumes:
      # - /path/to/stronghold:/app/res/stronghold
      - ../../agent_event_publisher_http/config.yml:/app/agent_event_publisher_http/config.yml
